# Generated by Django 4.1.4 on 2023-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute_App", "0003_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Club_Name", models.CharField(max_length=50)),
                ("Open_Time", models.CharField(default="10:00 AM", max_length=50)),
                ("Close_Time", models.CharField(default="04:00 PM", max_length=50)),
                ("Head_Of_Club", models.CharField(default="", max_length=50)),
                ("Contact", models.CharField(default="", max_length=10)),
            ],
            options={
                "db_table": "club",
            },
        ),
    ]
