# Generated by Django 4.1.4 on 2023-01-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institute_App", "0006_department_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
